---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC/UtQ3AORHScAfZAsGCxjyj/jSG67CzZ8c5bshTDJLt6zA08Fya3+XwVnX+sh+GEgrlSl9lBbAwvz62Ik82yvf31hWEW7gtrS8cOt8ezTsgluNvx/c/YFtd2/wqWL3ROaIWknaBeaza330BIIPiJJVXrbR618sApzrUSl3V8oZagOaH1lBFDGwngw2t8e4cxu4tPHpLN29k/JVDVS2cSqm4yPAmdBZ1TDbJYNWU4wqy2nnABFXxiRSTj8F+M5Mq+Xxo9oBs/3jM+6//z/Ml6cmhm5DO7iqrWUO9jAPYoAdc//wQrO0eFu2Oiiaci0M764GDUZivVQhHfzXfcz3d6iyLJkMHrVQFJIiMVu3N6nxQ8OtMXeTp3hGZl7bub9GrcerMfSvpxDZ9AWuEJ3DUC1IwPsiwDDB4PWL2HPFPzd6TiFC4KQklCHYoUKeuqF0i/frsSBl44RD5V/6bTlJu4q28QGZoRHt61W8wBldaIPH+Im5iX4gKv7MsYTqT3OFSRjNkeV74MjrUnYjD5Kl0AyQLkSCLWvWilHAylplLWvXiCbVhuPkX3BQdogp3ZvhQuSRuABmR7XDpooesOTRWaPjOoPmh7R1cw+U+BafC20bl+UmY2UCWdwwAXEp3Etl/SbJ6cpPbZ6w8L7YdruUVaXf/u25CRcUj3EehVFXkTom/91C34Xyg8qQiiqADeGFOw9XduMjP/DIa7akNHkq9ROFsDtSQkqrKPzO910/wsqlPlyRP9qAW8y1zeNNbtnrSINe3Ym0yg==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
